blog/urls.py
from django.conf.urls import url
from .views import index, view_blog, add_blog, update_blog, delete_comment

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^view_blog/(?P<blog_id>\d+)$', view_blog, name="view-blog"),
	url(r'^add_blog$', add_blog, name='add-blog'),
	url(r'^update_blog/(?P<blog_id>\d+)$', update_blog, name='update-blog'),
	url(r'^delete_comment/(?P<comment_id>\d+)$', delete_comment, name='delete-comment'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
	url(r'^', include(('blog.urls','blog'), namespace="blog")),
	path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=255)
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "%s" % self.title

class Comment(models.Model):
	author = models.CharField(max_length=60)
	body = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey('Post', on_delete=models.CASCADE)

blog/forms.py
from django import forms
from .models import Post

class BlogForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = "__all__"

class CommentForm(forms.Form):
	author = forms.CharField(
		max_length=60,
		widget=forms.TextInput(attrs={
			"class": "form-control",
			"placeholder": "Your Name"
		})
	)
	body = forms.CharField(widget=forms.Textarea(
		attrs={
			"class": "form-control",
			"placeholder": "Leave a comment!"
		})
	)

blog/views.py
from django.shortcuts import render
from .models import Post, Comment
from .forms import CommentForm, BlogForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

# Create your views here.
def index(request):
	template = "index.html"
	posts = Post.objects.all().order_by('-created_on')
	context = {
		"posts": posts,
	}
	return render(request, template, context)

def add_blog(request):
	template = "add_blog.html"
	if request.method == "POST":
		form = BlogForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'blog_form': BlogForm(),
		}
	return render(request, template, context)

def update_blog(request, blog_id):
	template = "update_blog.html"
	post = Post.objects.get(id=int(blog_id))
	if request.method == "POST":
		form = BlogForm(request.POST, instance=post)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse_lazy('blog:index'))
	else:
		context = {
			'blog_form': BlogForm(instance=post),
		}

	return render(request, template, context)

def view_blog(request, blog_id):
	template = "view_blog.html"
	post = Post.objects.get(id=blog_id)

	form = CommentForm()
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = Comment(
				author=form.cleaned_data["author"],
				body=form.cleaned_data["body"],
				post=post
			)
			comment.save()

	comments = Comment.objects.filter(post=post)
	context = {
		"post": post,
		"comments": comments,
		"form": form,
	}

	return render(request, template, context)

def delete_comment(request, comment_id):
	comment = Comment.objects.get(id=int(comment_id))
	comment.delete()
	return HttpResponseRedirect(reverse_lazy('blog:index'))

templates/add_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<header class="navbar bg-danger text-light">
			<h2>Add New Blog</h2>
		</header>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<form role="form" action="" method="POST">
						{% csrf_token %}
						<table class="table table-bordered table-striped">
							<tbody>
								<tr>
									<th>Title</th>
									<th class="form-control">{{ blog_form.title }}</th>
								</tr>
								<tr>
									<th>Body</th>
									<th class="form-control">{{ blog_form.body }}</th>
								</tr>
							</tbody>
						</table>
						<button type="submit" class="btn btn-danger">Save</button>
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

templates/index.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<header class="navbar bg-danger text-light">
			<h1>Blog App</h1>
		</header><br/>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<a href="{% url 'blog:add-blog' %}" class="btn btn-secondary">Add New Blog</a>
				</div>
			</div>
		</div><br/>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					{% for post in posts %}
						<h3 class="mb-0">
							<a class="text-danger" href="{% url 'blog:view-blog' post.id %}">{{ post.title }}</a>
						</h3>
						<small>
							<a class="text-dark" href="{% url 'blog:update-blog' post.id %}">Edit</a>
						</small>
						<p>{{ post.body | slice:":400" }}...</p>
						<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
	</body>
</html>

templates/update_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<header class="navbar bg-danger text-light">
			<h2>Edit Blog</h2>
		</header>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<form role="form" action="" method="POST">
						{% csrf_token %}
						<table class="table table-bordered table-striped">
							<tbody>
								<tr>
									<th>Title</th>
									<th class="form-control">{{ blog_form.title }}</th>
								</tr>
								<tr>
									<th>Body</th>
									<th class="form-control">{{ blog_form.body }}</th>
								</tr>
							</tbody>
						</table>
						<button type="submit" class="btn btn-danger">Save</button>
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

templates/view_blog.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<header class="navbar bg-danger text-light d-block text-center">
			<h2>{{ post.title }}</h2>
		</header>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>{{ post.body | linebreaks }}</p>
					<h4>Leave a comment:</h4>
					<form action="/view_blog/{{ post.id }}" method="post">
						{% csrf_token %}
						<div class="form-group">
							{{ form.author }}
						</div>
						<div class="form-group">
							{{ form.body }}
						</div>
						<button type="submit" class="btn btn-danger">Submit</button>
					</form>
					<h4>Comments:</h4>
					{% for comment in comments %}
					<p>
						<b>{{ comment.author }}</b> wrote:<br/>
						<small>
							<a class="text-dark" href="{% url 'blog:delete-comment' comment.id %}">Delete Comment</a>
						</small>
					</p>
					<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ comment.body }}</p>
					<hr>
					{% endfor %}
				</div>
			</div>
		</div>
	</body>
</html>